[colors.primary]
background = "#F4E6D2"
foreground = "#2B2626"

[colors.normal]
black = "#181515"
red = "#CB2424"
green = "#9BA636"
yellow = "#E98F21"
blue = "#34709B"
magenta = "#CF2D8E"
cyan = "#3E9F85"
white = "#B79F9F"

[colors.bright]
black = "#2B2626"
red = "#de4444"
green = "#b8c44b"
yellow = "#eea64f"
blue = "#428bc0"
magenta = "#da55a5"
cyan = "#54bca0"
white = "#DBC6C2"
